spring:
  data:
    redis:
      host: redis-dev.env-dev.svc.cluster.local
      port: 6379

  kafka:
    bootstrap-servers: dev-kafka-kafka0-headless:29092,dev-kafka-kafka1-headless:29092

gateway:
  jwt:
    jwks-uri: http://dev-keycloak-svc:8080/realms/adapstory/protocol/openid-connect/certs
    issuer: https://auth.dev.adapstory.com/realms/adapstory
    audience: adapstory-plugin-gateway

  bc02:
    base-url: http://dev-plugin-lifecycle-svc.env-dev.svc.cluster.local:8080

  routes:
    content: http://dev-data-model-engine-svc.env-dev.svc.cluster.local:8081
    submission: http://dev-submission-svc.env-dev.svc.cluster.local:8080
    identity: http://dev-identity-service-svc.env-dev.svc.cluster.local:8082
    plugin: http://dev-plugin-lifecycle-svc.env-dev.svc.cluster.local:8080
    tenant: http://dev-multi-tenant-runtime-svc.env-dev.svc.cluster.local:8080

logging:
  level:
    com.adapstory.gateway: DEBUG
