spring:
  data:
    redis:
      host: redis.dev.adapstory.com
      port: 6379

  kafka:
    bootstrap-servers: kafka.dev.adapstory.com:9092

gateway:
  jwt:
    jwks-uri: https://auth.dev.adapstory.com/realms/plugins/protocol/openid-connect/certs
    issuer: https://auth.dev.adapstory.com/realms/plugins

  routes:
    content: http://adapstory-data-model-engine.dev.svc.cluster.local:8080
    submission: http://adapstory-submission.dev.svc.cluster.local:8080
    identity: http://adapstory-identity.dev.svc.cluster.local:8080
    plugin: http://adapstory-plugin-lifecycle.dev.svc.cluster.local:8080
    tenant: http://adapstory-multi-tenant-runtime.dev.svc.cluster.local:8080

logging:
  level:
    com.adapstory.gateway: DEBUG
